import type { TrackerSection } from './trackerTypes';

export const DEFAULT_PROGRAM_SECTIONS: TrackerSection[] = [
  {
    name: 'Speakers',
    items: [
      {
        id: 'spk-1',
        item: 'Keynote Speaker — Opening Ceremony',
        target: '1',
        confirmed: '1',
        percentComplete: 100,
        status: 'on-track',
        owner: 'Programme Lead',
        nextStep: 'Confirm travel logistics',
        risk: 'None',
      },
      {
        id: 'spk-2',
        item: 'Plenary Speakers (Industry Leaders)',
        target: '10',
        confirmed: '4',
        percentComplete: 40,
        status: 'at-risk',
        owner: 'Programme Lead',
        nextStep: 'Follow up with 3 pending confirmations',
        risk: 'Low response rate from East Africa region',
      },
      {
        id: 'spk-3',
        item: 'Technical Session Speakers',
        target: '20',
        confirmed: '6',
        percentComplete: 30,
        status: 'behind',
        owner: 'Programme Coordinator',
        nextStep: 'Send second round of invitations',
        risk: 'Late confirmations may affect schedule build',
      },
      {
        id: 'spk-4',
        item: 'Panel Moderators',
        target: '6',
        confirmed: '3',
        percentComplete: 50,
        status: 'at-risk',
        owner: 'Programme Coordinator',
        nextStep: 'Confirm 2 remaining moderators by end of week',
        risk: 'One moderator travelling from West Africa — visa needed',
      },
      {
        id: 'spk-5',
        item: 'Closing Ceremony Speaker',
        target: '1',
        confirmed: '0',
        percentComplete: 0,
        status: 'behind',
        owner: 'Programme Lead',
        nextStep: 'Shortlist candidates and send invitations',
        risk: 'High-profile speaker may have scheduling conflict',
      },
      {
        id: 'spk-6',
        item: 'Youth & Innovation Spotlight Speakers',
        target: '2',
        confirmed: '2',
        percentComplete: 100,
        status: 'on-track',
        owner: 'Youth Programme Lead',
        nextStep: 'Brief speakers on format and timing',
        risk: 'None',
      },
    ],
  },
  {
    name: 'Topics',
    items: [
      {
        id: 'top-1',
        item: 'Sustainability & Climate-Smart Coffee Farming',
        target: '1',
        confirmed: '1',
        percentComplete: 100,
        status: 'on-track',
        owner: 'Programme Lead',
        nextStep: 'Assign speaker and finalize abstract',
        risk: 'None',
      },
      {
        id: 'top-2',
        item: 'Specialty Coffee & Tea Market Trends',
        target: '1',
        confirmed: '1',
        percentComplete: 100,
        status: 'on-track',
        owner: 'Programme Coordinator',
        nextStep: 'Confirm speaker brief',
        risk: 'None',
      },
      {
        id: 'top-3',
        item: 'Finance & Investment in the Coffee Value Chain',
        target: '1',
        confirmed: '0',
        percentComplete: 0,
        status: 'behind',
        owner: 'Programme Lead',
        nextStep: 'Identify speaker from financial sector',
        risk: 'No confirmed speaker yet',
      },
      {
        id: 'top-4',
        item: 'Export Regulations & Trade Corridors',
        target: '1',
        confirmed: '1',
        percentComplete: 100,
        status: 'on-track',
        owner: 'Programme Coordinator',
        nextStep: 'Share presentation template',
        risk: 'None',
      },
    ],
  },
  {
    name: 'Panels',
    items: [
      {
        id: 'pan-1',
        item: 'Women in Coffee & Tea Leadership Panel',
        target: '1',
        confirmed: '1',
        percentComplete: 100,
        status: 'on-track',
        owner: 'Gender & Inclusion Lead',
        nextStep: 'Confirm all 4 panelists and moderator',
        risk: 'None',
      },
      {
        id: 'pan-2',
        item: 'Youth Innovation in Agri-Business Panel',
        target: '1',
        confirmed: '0',
        percentComplete: 20,
        status: 'at-risk',
        owner: 'Youth Programme Lead',
        nextStep: 'Confirm moderator and 2 more panelists',
        risk: 'Panelist availability in June uncertain',
      },
      {
        id: 'pan-3',
        item: 'Policy & Regulatory Frameworks for Exports',
        target: '1',
        confirmed: '1',
        percentComplete: 100,
        status: 'on-track',
        owner: 'Programme Lead',
        nextStep: 'Share panel outline with participants',
        risk: 'None',
      },
    ],
  },
  {
    name: 'Masterclasses',
    items: [
      {
        id: 'mc-1',
        item: 'Coffee Cupping & Sensory Evaluation',
        target: '1',
        confirmed: '1',
        percentComplete: 100,
        status: 'on-track',
        owner: 'Barista Lead',
        nextStep: 'Arrange equipment and venue setup',
        risk: 'None',
      },
      {
        id: 'mc-2',
        item: 'Tea Blending & Packaging Masterclass',
        target: '1',
        confirmed: '0',
        percentComplete: 30,
        status: 'at-risk',
        owner: 'Programme Coordinator',
        nextStep: 'Confirm facilitator and supply list',
        risk: 'Facilitator sourcing still in progress',
      },
      {
        id: 'mc-3',
        item: 'Digital Marketing for Coffee & Tea Brands',
        target: '1',
        confirmed: '0',
        percentComplete: 0,
        status: 'behind',
        owner: 'Marketing Lead',
        nextStep: 'Identify and brief digital marketing expert',
        risk: 'May be cut if speaker not found by April 15',
      },
    ],
  },
  {
    name: 'Barista Competition',
    items: [
      {
        id: 'bc-1',
        item: 'Competition Rules & Format Finalized',
        target: '1',
        confirmed: '1',
        percentComplete: 100,
        status: 'on-track',
        owner: 'Barista Lead',
        nextStep: 'Publish rulebook to registrants',
        risk: 'None',
      },
      {
        id: 'bc-2',
        item: 'Judges Panel Confirmed',
        target: '5',
        confirmed: '3',
        percentComplete: 60,
        status: 'at-risk',
        owner: 'Barista Lead',
        nextStep: 'Confirm 2 remaining international judges',
        risk: 'International judge travel costs unconfirmed',
      },
      {
        id: 'bc-3',
        item: 'Competitor Registrations',
        target: '30',
        confirmed: '12',
        percentComplete: 40,
        status: 'at-risk',
        owner: 'Registration Team',
        nextStep: 'Open registration to all African barista networks',
        risk: 'Late registration may limit competitor diversity',
      },
    ],
  },
  {
    name: 'Award Gala',
    items: [
      {
        id: 'ag-1',
        item: 'Award Categories Defined',
        target: '8',
        confirmed: '8',
        percentComplete: 100,
        status: 'on-track',
        owner: 'Programme Lead',
        nextStep: 'Announce categories to stakeholders',
        risk: 'None',
      },
      {
        id: 'ag-2',
        item: 'Nominations Process Open',
        target: '1',
        confirmed: '0',
        percentComplete: 0,
        status: 'behind',
        owner: 'Programme Coordinator',
        nextStep: 'Launch online nominations portal',
        risk: 'Nominations portal not yet built',
      },
      {
        id: 'ag-3',
        item: 'Gala MC / Host Confirmed',
        target: '1',
        confirmed: '0',
        percentComplete: 0,
        status: 'behind',
        owner: 'Events Lead',
        nextStep: 'Contact shortlisted MC candidates',
        risk: 'High-profile MC may request significant fee',
      },
    ],
  },
];

export const DEFAULT_OPERATIONS_SECTIONS: TrackerSection[] = [
  {
    name: 'Venue Confirmation',
    items: [
      {
        id: 'vc-1',
        item: 'Main Exhibition Hall Booking',
        target: '1',
        confirmed: '1',
        percentComplete: 100,
        status: 'on-track',
        owner: 'Operations Lead',
        nextStep: 'Sign final contract and pay deposit',
        risk: 'None',
      },
      {
        id: 'vc-2',
        item: 'Conference Rooms (Breakout Sessions)',
        target: '4',
        confirmed: '4',
        percentComplete: 100,
        status: 'on-track',
        owner: 'Operations Coordinator',
        nextStep: 'Confirm room layout requirements with venue',
        risk: 'None',
      },
      {
        id: 'vc-3',
        item: 'Gala Dinner Venue',
        target: '1',
        confirmed: '0',
        percentComplete: 50,
        status: 'at-risk',
        owner: 'Events Lead',
        nextStep: 'Final site visit and negotiate F&B package',
        risk: 'Two venue options — decision needed by April 10',
      },
    ],
  },
  {
    name: 'Exhibition Build-up',
    items: [
      {
        id: 'eb-1',
        item: 'Stand Builder / Contractor Appointed',
        target: '1',
        confirmed: '1',
        percentComplete: 100,
        status: 'on-track',
        owner: 'Operations Lead',
        nextStep: 'Submit booth specs and layout to contractor',
        risk: 'None',
      },
      {
        id: 'eb-2',
        item: 'Shell Scheme Booths Ready',
        target: '152',
        confirmed: '80',
        percentComplete: 53,
        status: 'at-risk',
        owner: 'Operations Coordinator',
        nextStep: 'Confirm final booth count with contractor',
        risk: 'Contractor capacity may limit booth numbers',
      },
      {
        id: 'eb-3',
        item: 'Branding & Signage Installation',
        target: '1',
        confirmed: '0',
        percentComplete: 10,
        status: 'behind',
        owner: 'Marketing Lead',
        nextStep: 'Approve final design files and send to print',
        risk: 'Print lead time 3 weeks — artwork must be approved by May 1',
      },
    ],
  },
  {
    name: 'Floor Plan',
    items: [
      {
        id: 'fp-1',
        item: 'Floor Plan Draft v1 Approved',
        target: '1',
        confirmed: '1',
        percentComplete: 100,
        status: 'on-track',
        owner: 'Operations Lead',
        nextStep: 'Share with exhibitors for booth selection',
        risk: 'None',
      },
      {
        id: 'fp-2',
        item: 'Exhibitor Booth Assignments Sent',
        target: '152',
        confirmed: '45',
        percentComplete: 30,
        status: 'behind',
        owner: 'Operations Coordinator',
        nextStep: 'Complete assignments for all confirmed exhibitors',
        risk: 'Latecomers may have limited booth choice',
      },
      {
        id: 'fp-3',
        item: 'Catering & Networking Zones Mapped',
        target: '1',
        confirmed: '1',
        percentComplete: 100,
        status: 'on-track',
        owner: 'Operations Lead',
        nextStep: 'Brief F&B vendor on zone layout',
        risk: 'None',
      },
    ],
  },
  {
    name: 'Production (AV & Staging)',
    items: [
      {
        id: 'av-1',
        item: 'AV Supplier / Production Company Appointed',
        target: '1',
        confirmed: '1',
        percentComplete: 100,
        status: 'on-track',
        owner: 'Operations Lead',
        nextStep: 'Provide technical rider and schedule',
        risk: 'None',
      },
      {
        id: 'av-2',
        item: 'Main Stage Setup (Plenary)',
        target: '1',
        confirmed: '0',
        percentComplete: 40,
        status: 'at-risk',
        owner: 'Operations Coordinator',
        nextStep: 'Confirm stage dimensions and backdrop design',
        risk: 'Stage design pending sponsor branding approval',
      },
      {
        id: 'av-3',
        item: 'Live Streaming Setup',
        target: '1',
        confirmed: '0',
        percentComplete: 0,
        status: 'behind',
        owner: 'Digital Lead',
        nextStep: 'Brief digital partner on streaming requirements',
        risk: 'No confirmed streaming partner yet — needed by May 1',
      },
    ],
  },
  {
    name: 'Delegate Management',
    items: [
      {
        id: 'dm-1',
        item: 'Registration Platform Live',
        target: '1',
        confirmed: '1',
        percentComplete: 100,
        status: 'on-track',
        owner: 'Digital Lead',
        nextStep: 'Monitor registrations and send confirmation emails',
        risk: 'None',
      },
      {
        id: 'dm-2',
        item: 'Accreditation & Badge Design',
        target: '1',
        confirmed: '0',
        percentComplete: 60,
        status: 'at-risk',
        owner: 'Operations Coordinator',
        nextStep: 'Finalize badge design and print specifications',
        risk: 'Badge design pending final delegate categories',
      },
      {
        id: 'dm-3',
        item: 'Airport Transfers & Accommodation List',
        target: '100',
        confirmed: '30',
        percentComplete: 30,
        status: 'behind',
        owner: 'Hosted Buyers Lead',
        nextStep: 'Collect travel details from all hosted delegates',
        risk: 'Many hosted buyers yet to confirm travel dates',
      },
    ],
  },
  {
    name: 'Matchmaking Platform',
    items: [
      {
        id: 'mp-1',
        item: 'Platform Vendor Selected',
        target: '1',
        confirmed: '1',
        percentComplete: 100,
        status: 'on-track',
        owner: 'Digital Lead',
        nextStep: 'Complete data migration and profile setup',
        risk: 'None',
      },
      {
        id: 'mp-2',
        item: 'Buyer & Exhibitor Profiles Uploaded',
        target: '252',
        confirmed: '60',
        percentComplete: 24,
        status: 'behind',
        owner: 'Digital Lead',
        nextStep: 'Send profile completion reminders to participants',
        risk: 'Low completion rate may reduce meeting bookings',
      },
      {
        id: 'mp-3',
        item: 'Meeting Scheduler Open to Participants',
        target: '1',
        confirmed: '0',
        percentComplete: 0,
        status: 'behind',
        owner: 'Digital Lead',
        nextStep: 'Open scheduler once 80% profiles are complete',
        risk: 'Delayed profile upload delays meeting scheduler launch',
      },
    ],
  },
];
